cimport dtype from numpy
The dtype from numpy lacks a 'kind' field. So you get:

Traceback (most recent call last):
  File "/home/esc/gw/bcolz/bcolz/tests/test_attrs.py", line 137, in test03
    cn = self.getobject()
  File "/home/esc/gw/bcolz/bcolz/tests/test_attrs.py", line 28, in getobject
    count=10, rootdir=self.rootdir)
  File "bcolz/toplevel.py", line 227, in fromiter
    obj.flush()
  File "bcolz/ctable.py", line 1204, in flush
    self.cols[name].flush()
  File "bcolz/carray_ext.pyx", line 2540, in bcolz.carray_ext.carray.flush (bcolz/carray_ext.c:31125)
    chunk_ = chunk(self.lastchunkarr[:leftover_atoms], self.dtype,
  File "bcolz/carray_ext.pyx", line 304, in bcolz.carray_ext.chunk.__cinit__ (bcolz/carray_ext.c:3963)
    self.typekind = dtype_.kind
TypeError: an integer is required

After some discussion in:

http://mail.scipy.org/pipermail/numpy-discussion/2014-December/071938.html

There is now a hacky solution in place. See the comments in the source-code for
details.

Also I kept getting:

Traceback (most recent call last):
  File "/home/esc/gw/bcolz/bcolz/tests/test_attrs.py", line 137, in test03
    cn = self.getobject()
  File "/home/esc/gw/bcolz/bcolz/tests/test_attrs.py", line 28, in getobject
    count=10, rootdir=self.rootdir)
  File "bcolz/toplevel.py", line 227, in fromiter
    obj.flush()
  File "bcolz/ctable.py", line 1204, in flush
    self.cols[name].flush()
  File "bcolz/carray_ext.pyx", line 2545, in bcolz.carray_ext.carray.flush (bcolz/carray_ext.c:31139)
    chunk_ = chunk(self.lastchunkarr[:leftover_atoms], self.dtype,
  File "bcolz/carray_ext.pyx", line 318, in bcolz.carray_ext.chunk.__cinit__ (bcolz/carray_ext.c:4070)
    itemsize = dtype_.elsize
AttributeError: 'numpy.dtype' object has no attribute 'elsize'

This should work, but because it doesn't I simply replaced 'elsize' with
'itemsize.